name = "EconoSim"
uuid = "cc8cb6e0-4c11-4d04-b964-59e7aacda730"
authors = ["Stef Kuypers <stef@happonomy.org>"]
version = "0.1.0"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
Agents = "4.0"
DataStructures = "0.18"
